environment:
  matrix:

# VS 2015
  - VS_VERSION: Visual Studio 14
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    platform: x86

# VS 2017
  - VS_VERSION: Visual Studio 15
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64

shallow_clone: true

build_script:
  - echo build_script
  - set "BUILD_FOLDER=%APPVEYOR_BUILD_FOLDER:\=/%"
  - if "%platform%" == "x64" SET VS_FULL=%VS_VERSION% Win64
  - if "%platform%" == "x86" SET VS_FULL=%VS_VERSION%
  - echo "%VS_FULL%"
# Build vcpkg
  - git clone https://github.com/microsoft/vcpkg
  - cd vcpkg
  - bootstrap-vcpkg.bat
  - set PATH=%CD%;%PATH%
  - cd ..
# Install libtiff
  - vcpkg install tiff:"%platform%"-windows
# Build libtiff
#  - git clone --depth=1 https://gitlab.com/libtiff/libtiff
#  - cd libtiff
#  - mkdir build_cmake
#  - cd build_cmake
#  - cmake -G "%VS_FULL%" .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%BUILD_FOLDER%/install"
#  - cmake --build . --config Release --target install
#  - cd ..
#  - cd ..
# Install sqlite (PROJ dependency)
  - vcpkg install sqlite3:"%platform%"-windows
  - ps: |
        appveyor DownloadFile https://sqlite.org/2018/sqlite-tools-win32-x86-3250100.zip
        7z x sqlite-tools-win32-x86-3250100.zip
        copy sqlite-tools-win32-x86-3250100/sqlite3.exe .
# Build PROJ
  - git clone --depth=1 -b 6.3 https://github.com/OSGeo/PROJ proj
  - cd proj
  - mkdir build
  - cd build
  - copy ..\..\sqlite3.exe .
  - copy c:\projects\libgeotiff\vcpkg\installed\%platform%-windows\bin\sqlite3.dll .
  - set PATH=%CD%;%PATH%
  - cmake -G "%VS_FULL%" .. -DCMAKE_BUILD_TYPE=Release -DPROJ_TESTS=OFF -DBUILD_LIBPROJ_SHARED=ON -DCMAKE_TOOLCHAIN_FILE=c:/projects/libgeotiff/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX="%BUILD_FOLDER%/install"
  - cmake --build . --config Release --target install
  - cd ..
  - cd ..
# Build libgeotiff
  - cd libgeotiff
  - mkdir build
  - cd build
  - cmake -G "%VS_FULL%" .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release  -DCMAKE_C_FLAGS="/WX" -DCMAKE_CXX_FLAGS="/WX"  -DCMAKE_INSTALL_PREFIX="%BUILD_FOLDER%/install" -DPROJ_INCLUDE_DIR="%BUILD_FOLDER%/install/include" -DPROJ_LIBRARY="%BUILD_FOLDER%/install/lib/proj.lib" -DCMAKE_TOOLCHAIN_FILE=c:/projects/libgeotiff/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake --build . --config Release --target install

test_script:

deploy: off

